#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of DP-2

sleep 0.3

bspc monitor DP-2 -d 1 2 3 4
bspc monitor DP-1 -d 5 6 7 8

bspc monitor DP-2 -f

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/1276644.jpg
picom --config ~/.config/picom/picom.conf
sleep 0.5 && pkill -USR1 -x sxhkd
