# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EFE9DF
background         #1B1A19
cursor             #979084

active_tab_foreground     #1B1A19
active_tab_background     #EFE9DF
inactive_tab_foreground   #EFE9DF
inactive_tab_background   #1B1A19

active_border_color   #EFE9DF
inactive_border_color #1B1A19
bell_border_color     #2E291E

color0      #42413F
color1		#2E291E
color2		#2E2A1F
color3		#4D4534
color4		#625845
color5		#9A8D77
color6		#9D917A
color7		#E0D8C9
color8		#9D978C
color9		#3D3628
color10		#3E3729
color11		#675C46
color12		#82755C
color13		#CEBD9F
color14		#D2C1A3
color15		#E0D8C9
